export enum QuestionType {
  RATING_TO_5 = 'RATING_TO_5',
  RATING_TO_10 = 'RATING_TO_10',
  YES_OR_NOT = 'YES_OR_NOT',
  OPEN_WRITING = 'OPEN_WRITING',
  OPEN_OPTIONS = 'OPEN_OPTIONS',
  CHOOSE_OPTION = 'CHOOSE_OPTION'
}