export enum AttentionStatus {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    TERMINATED = 'TERMINATED',
    CANCELLED = 'CANCELLED',
    REACTIVATED = 'REACTIVATED',
    RATED = 'RATED'
}