export enum AttentionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  TERMINATED = 'TERMINATED',
  CANCELLED = 'CANCELLED',
  SKIPED = 'SKIPED',
  USER_CANCELLED = 'USER_CANCELLED',
  REACTIVATED = 'REACTIVATED',
  RATED = 'RATED',
  TERMINATED_RESERVE_CANCELLED = 'TERMINATED_RESERVE_CANCELLED',
}
