export enum AttentionStage {
  PENDING = 'PENDING',
  CHECK_IN = 'CHECK_IN',
  PRE_CONSULTATION = 'PRE_CONSULTATION',
  CONSULTATION = 'CONSULTATION',
  POST_CONSULTATION = 'POST_CONSULTATION',
  CHECKOUT = 'CHECKOUT',
  TERMINATED = 'TERMINATED',
  CANCELLED = 'CANCELLED',
}







