export enum DocumentType {
  STANDARD = 'STANDARD',
  COMMERCE = 'COMMERCE',
  CLIENT = 'CLIENT',
}

export enum DocumentCategory {
  // Clinical Documents
  LABORATORY_RESULTS = 'LABORATORY_RESULTS',
  IMAGING_STUDIES = 'IMAGING_STUDIES',
  PATHOLOGY_REPORTS = 'PATHOLOGY_REPORTS',
  CONSULTATION_NOTES = 'CONSULTATION_NOTES',
  DISCHARGE_SUMMARIES = 'DISCHARGE_SUMMARIES',
  REFERRAL_LETTERS = 'REFERRAL_LETTERS',
  PRESCRIPTION_RECORDS = 'PRESCRIPTION_RECORDS',

  // Patient Documents
  CONSENT_FORMS = 'CONSENT_FORMS',
  INSURANCE_CARDS = 'INSURANCE_CARDS',
  IDENTIFICATION = 'IDENTIFICATION',
  MEDICAL_HISTORY = 'MEDICAL_HISTORY',
  ALLERGIES_MEDICATIONS = 'ALLERGIES_MEDICATIONS',

  // Administrative
  BILLING_DOCUMENTS = 'BILLING_DOCUMENTS',
  APPOINTMENT_CONFIRMATIONS = 'APPOINTMENT_CONFIRMATIONS',

  // External Documents
  EXTERNAL_REPORTS = 'EXTERNAL_REPORTS',
  PREVIOUS_TREATMENTS = 'PREVIOUS_TREATMENTS',
  SPECIALIST_REPORTS = 'SPECIALIST_REPORTS',

  // General
  OTHER = 'OTHER'
}

export enum DocumentUrgency {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum DocumentStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  REVIEWED = 'REVIEWED',
  ARCHIVED = 'ARCHIVED',
  EXPIRED = 'EXPIRED',
  ACTIVE = 'ACTIVE'
}
