export enum PatientHistoryControlReason {
    EXAM_REVISION = 'EXAM_REVISION',
    TREATEMENT_REVISION = 'TREATEMENT_REVISION',
    PROCEDURE_REVISION = 'PROCEDURE_REVISION',
    GENERAL_REVISION = 'GENERAL_REVISION',
    OTHER = 'OTHER'
}