export enum SurveyType {
  SIMPLE_CSAT = 'SIMPLE_CSAT',
  EXTENDED_CSAT = 'EXTENDED_CSAT',
  SIMPLE_NPS = 'SIMPLE_NPS',
  EXTENDED_NPS = 'EXTENDED_NPS',
  SIMPLE_CSAT_NPS = 'SIMPLE_CSAT_NPS',
  PERSONALIZED_SURVEY = 'PERSONALIZED_SURVEY',
}
