export enum NotificationType {
    ESTUTURNO = 'ESTUTURNO',
    FALTANCINCO = 'FALTANCINCO',
    FALTAUNO = 'FALTAUNO',
    TUTURNO = 'TUTURNO',
    ENCUESTA = 'ENCUESTA',
    MONTHLY_COMMERCE_STATISTICS = 'MONTHLY_COMMERCE_STATISTICS'
}