import { Collaborator } from '../../collaborator/model/collaborator.entity';
import { Commerce } from '../../commerce/model/commerce.entity';
import { Module } from '../../module/module.entity';
import { PaymentConfirmation } from '../../payment/model/payment-confirmation';
import { Queue } from '../../queue/model/queue.entity';
import { User } from '../../user/model/user.entity';
import { Block } from '../model/attention.entity';
import { AttentionStage } from '../model/attention-stage.enum';
import { AttentionStageHistory } from '../model/attention-stage-history.entity';

export class AttentionDetailsDto {
  id: string;
  commerceId: string;
  collaboratorId: string;
  createdAt: Date;
  endAt: Date;
  number: number;
  queueId: string;
  serviceId: string;
  status: string;
  userId: string;
  moduleId: string;
  comment: string;
  surveyId: string;
  reactivatedAt: Date;
  reactivated: boolean;
  duration: number;
  type: string;
  assistingCollaboratorId: string;
  channel: string;
  queue: Queue;
  commerce: Commerce;
  user: User;
  ratedAt: Date;
  rateDuration: number;
  collaborator: Collaborator;
  module: Module;
  notificationOn: boolean;
  notificationEmailOn: boolean;
  block: Block;
  paid: boolean;
  paidAt: Date;
  paymentConfirmationData: PaymentConfirmation;
  servicesId: string[];
  servicesDetails: object[];
  clientId: string;
  surveyPostAttentionDateScheduled: string;
  processedAt: Date;
  telemedicineSessionId?: string;
  telemedicineConfig?: {
    type: string;
    scheduledAt: Date | string;
    recordingEnabled?: boolean;
    notes?: string;
  };
  telemedicineInfo?: {
    patientConnectedAt?: Date | string;
    doctorConnectedAt?: Date | string;
    endedAt?: Date | string;
    endedBy?: string;
    duration?: number; // Duración en minutos
  };
  currentStage?: AttentionStage;
  stageHistory?: AttentionStageHistory[];
  notificationCheckInSent?: boolean;
  professionalId?: string;
  professionalName?: string;
  professionalCommissionType?: string;
  professionalCommissionValue?: number;
  professionalCommissionAmount?: number;
  professionalCommissionNotes?: string;
  bookingId?: string;
  bookingScheduledTime?: Date | string;
}
